site_name: grav_sim
repo_url: https://github.com/alvinng4/grav_sim
repo_name: alvinng4/grav_sim
docs_dir: .

nav:
  - Home:
    - README.md
  - Getting started:
    - Getting started: docs/getting_started/index.md
    - Installation in C: docs/getting_started/installation_in_c.md
    - Installation in Python: docs/getting_started/installation_in_python.md
    - Tutorial (Python): examples/tutorial.ipynb
  - Documentations:
    - docs/documentations/index.md
    - Barnes-Hut algorithm: docs/documentations/barnes_hut.md
    - Particle-Mesh algorithm: docs/documentations/particle_mesh.md
    - Reducing round off error: docs/documentations/reducing_round_off_error.md
    - Python API:
        - docs/documentations/PythonAPI/GravitySimulatorAPI.md
        - docs/documentations/PythonAPI/parameters.md
    - C API:
        - docs/documentations/CAPI/grav_sim.md
  - Examples:
    - examples/index.md
    - examples/solar_system_one_mil_yrs.ipynb
  - 12 steps to N-body simulation:
    - "12 steps to N-body simulation": 12_steps_to_n_body_simulation/index.md
theme:
  name: material
  logo: docs/orbit_logo.svg
  icon:
    repo: fontawesome/brands/github-alt
  custom_dir: overrides
  features:
    - navigation.instant
    - navigation.instant.progress
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - navigation.indexes
    - toc.integrate
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
    - content.tooltips
    
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
      primary: black
      accent: purple
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
      primary: black
      accent: purple
  
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.magiclink
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details:
  - pymdownx.superfences
  - pymdownx.blocks.tab:
      alternate_style: true
  - pymdownx.mark
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

copyright:
  "Copyright &copy; 2025 <a href='https://github.com/alvinng4'  target='_blank' rel='noopener'>Ching-Yin Ng</a>"

plugins:
  - search
  - bibtex:
      bib_file: docs/grav_sim.bib
  - mkdocs-jupyter:
      include: ["*.ipynb"]
      include_source: True
      execute: False
      custom_mathjax_url: "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.7/latest.js?config=TeX-AMS_CHTML-full,Safe"
  - same-dir
  - mkdocstrings
  - meta
  # - mkdocs-video

extra_javascript:
  - docs/javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js
