"""
Gravitational System class to represent a system of celestial bodies

Author: Ching Yin Ng
"""

import csv
from pathlib import Path
from typing import Optional

import numpy as np

from . import plotting
from . import utils


class GravitationalSystem:
    # Conversion factor from km^3 s^-2 to AU^3 d^-2
    CONVERSION_FACTOR = (86400**2) / (149597870.7**3)
    # GM values (km^3 s^-2)
    # ref: https://ssd.jpl.nasa.gov/doc/Park.2021.AJ.DE440.pdf
    GM_SI = {
        "Sun": 132712440041.279419,
        "Mercury": 22031.868551,
        "Venus": 324858.592000,
        "Earth": 398600.435507,
        "Mars": 42828.375816,
        "Jupiter": 126712764.100000,
        "Saturn": 37940584.841800,
        "Uranus": 5794556.400000,
        "Neptune": 6836527.100580,
        "Moon": 4902.800118,
        "Pluto": 975.500000,
        "Ceres": 62.62890,
        "Vesta": 17.288245,
    }
    # GM values (AU^3 d^-2)
    GM = {
        "Sun": 132712440041.279419 * CONVERSION_FACTOR,
        "Mercury": 22031.868551 * CONVERSION_FACTOR,
        "Venus": 324858.592000 * CONVERSION_FACTOR,
        "Earth": 398600.435507 * CONVERSION_FACTOR,
        "Mars": 42828.375816 * CONVERSION_FACTOR,
        "Jupiter": 126712764.100000 * CONVERSION_FACTOR,
        "Saturn": 37940584.841800 * CONVERSION_FACTOR,
        "Uranus": 5794556.400000 * CONVERSION_FACTOR,
        "Neptune": 6836527.100580 * CONVERSION_FACTOR,
        "Moon": 4902.800118 * CONVERSION_FACTOR,
        "Pluto": 975.500000 * CONVERSION_FACTOR,
        "Ceres": 62.62890 * CONVERSION_FACTOR,
        "Vesta": 17.288245 * CONVERSION_FACTOR,
    }
    # Solar system masses (M_sun^-1)
    SOLAR_SYSTEM_MASSES = {
        "Sun": 1.0,
        "Mercury": GM_SI["Mercury"] / GM_SI["Sun"],
        "Venus": GM_SI["Venus"] / GM_SI["Sun"],
        "Earth": GM_SI["Earth"] / GM_SI["Sun"],
        "Mars": GM_SI["Mars"] / GM_SI["Sun"],
        "Jupiter": GM_SI["Jupiter"] / GM_SI["Sun"],
        "Saturn": GM_SI["Saturn"] / GM_SI["Sun"],
        "Uranus": GM_SI["Uranus"] / GM_SI["Sun"],
        "Neptune": GM_SI["Neptune"] / GM_SI["Sun"],
        "Moon": GM_SI["Moon"] / GM_SI["Sun"],
        "Pluto": GM_SI["Pluto"] / GM_SI["Sun"],
        "Ceres": GM_SI["Ceres"] / GM_SI["Sun"],
        "Vesta": GM_SI["Vesta"] / GM_SI["Sun"],
    }
    # Gravitational constant (kg^-1 m^3 s^-2):
    CONSTANT_G_SI = 6.67430e-11
    # Gravitational constant (M_sun^-1 AU^3 d^-2):
    CONSTANT_G = GM["Sun"]

    # Solar system position and velocities data
    # Units: AU-D
    # Coordinate center: Solar System Barycenter
    # Data dated on A.D. 2024-Jan-01 00:00:00.0000 TDB
    # Computational data generated by NASA JPL Horizons System https://ssd.jpl.nasa.gov/horizons/
    SOLAR_SYSTEM_POS = {
        "Sun": [-7.967955691533730e-03, -2.906227441573178e-03, 2.103054301547123e-04],
        "Mercury": [
            -2.825983269538632e-01,
            1.974559795958082e-01,
            4.177433558063677e-02,
        ],
        "Venus": [
            -7.232103701666379e-01,
            -7.948302026312400e-02,
            4.042871428174315e-02,
        ],
        "Earth": [-1.738192017257054e-01, 9.663245550235138e-01, 1.553901854897183e-04],
        "Mars": [-3.013262392582653e-01, -1.454029331393295e00, -2.300531433991428e-02],
        "Jupiter": [3.485202469657674e00, 3.552136904413157e00, -9.271035442798399e-02],
        "Saturn": [8.988104223143450e00, -3.719064854634689e00, -2.931937777323593e-01],
        "Uranus": [1.226302417897505e01, 1.529738792480545e01, -1.020549026883563e-01],
        "Neptune": [
            2.983501460984741e01,
            -1.793812957956852e00,
            -6.506401132254588e-01,
        ],
        "Moon": [-1.762788124769829e-01, 9.674377513177153e-01, 3.236901585768862e-04],
        "Pluto": [1.720200478843485e01, -3.034155683573043e01, -1.729127607100611e00],
        "Ceres": [-1.103880510367569e00, -2.533340440444230e00, 1.220283937721780e-01],
        "Vesta": [-8.092549658731499e-02, 2.558381434460076e00, -6.695836142398572e-02],
    }
    SOLAR_SYSTEM_VEL = {
        "Sun": [4.875094764261564e-06, -7.057133213976680e-06, -4.573453713094512e-08],
        "Mercury": [
            -2.232165900189702e-02,
            -2.157207103176252e-02,
            2.855193410495743e-04,
        ],
        "Venus": [
            2.034068201002341e-03,
            -2.020828626592994e-02,
            -3.945639843855159e-04,
        ],
        "Earth": [
            -1.723001232538228e-02,
            -2.967721342618870e-03,
            6.382125383116755e-07,
        ],
        "Mars": [1.424832259345280e-02, -1.579236181580905e-03, -3.823722796161561e-04],
        "Jupiter": [
            -5.470970658852281e-03,
            5.642487338479145e-03,
            9.896190602066252e-05,
        ],
        "Saturn": [
            1.822013845554067e-03,
            5.143470425888054e-03,
            -1.617235904887937e-04,
        ],
        "Uranus": [
            -3.097615358317413e-03,
            2.276781932345769e-03,
            4.860433222241686e-05,
        ],
        "Neptune": [
            1.676536611817232e-04,
            3.152098732861913e-03,
            -6.877501095688201e-05,
        ],
        "Moon": [
            -1.746667306153906e-02,
            -3.473438277358121e-03,
            -3.359028758606074e-05,
        ],
        "Pluto": [2.802810313667557e-03, 8.492056438614633e-04, -9.060790113327894e-04],
        "Ceres": [
            8.978653480111301e-03,
            -4.873256528198994e-03,
            -1.807162046049230e-03,
        ],
        "Vesta": [
            -1.017876585480054e-02,
            -5.452367109338154e-04,
            1.255870551153315e-03,
        ],
    }

    # Built-in systems
    BUILT_IN_SYSTEMS = [
        "circular_binary_orbit",
        "eccentric_binary_orbit",
        "3d_helix",
        "sun_earth_moon",
        "figure-8",
        "pyth-3-body",
        "solar_system",
        "solar_system_plus",
    ]

    def __init__(self, name: Optional[str] = None) -> None:
        """Initialize GravitationalSystem object

        Parameters
        ----------
        name : str, optional
            Name of the system, by default None
        """
        if name is None:
            self.name = "Unnamed System"
        else:
            self.name = name
        self.x = np.zeros((0, 3), dtype=np.float64)
        self.v = np.zeros((0, 3), dtype=np.float64)
        self.m = np.zeros((0,), dtype=np.float64)
        self.objects_count = 0
        self.G = self.CONSTANT_G

    def add(
        self,
        x: list | np.ndarray,
        v: list | np.ndarray,
        m: float | list | np.ndarray,
    ) -> None:
        """Add one or multiple objects to the system

        Parameters
        ----------
        x : list or np.ndarray
            Position vector(s) of the object(s)
        v : list or np.ndarray
            Velocity vector(s) of the object(s)
        m : float
            Mass(es) of the object(s)
        """
        self.x = np.vstack((self.x, np.array(x, dtype=np.float64)))
        self.v = np.vstack((self.v, np.array(v, dtype=np.float64)))
        self.m = np.hstack((self.m, m))

        if isinstance(m, (list, np.ndarray)):
            self.objects_count += len(m)
        else:
            self.objects_count += 1

    def add_keplerian(
        self,
        semi_major_axis: float,
        eccentricity: float,
        inclination: float,
        argument_of_periapsis: float,
        longitude_of_ascending_node: float,
        true_anomaly: float,
        m: float,
        primary_object_index: Optional[int] = None,
        primary_object_x: Optional[np.ndarray] = None,
        primary_object_v: Optional[np.ndarray] = None,
        primary_object_m: Optional[float] = None,
    ):
        """
        Add a celestial body to the system using Keplerian elements

        Warning: This method use the G value from the system. Make sure
                 to set the correct G value before using this method.

        Parameters
        ----------
        semi_major_axis : float
            Semi-major axis
        eccentricity : float
            Eccentricity
        inclination : float
            Inclination
        argument_of_periapsis : float
            Argument of periapsis
        longitude_of_ascending_node : float
            Longitude of ascending node
        true_anomaly : float
            True anomaly
        m : float
            Mass
        primary_object_index : int, optional
            Index of the primary object
        primary_x : np.ndarray, optional
            Position vector of the primary object
        primary_v : np.ndarray, optional
            Velocity vector of the primary object
        primary_m : float, optional
            Mass of the primary object

        Raises
        ------
        ValueError
            If primary_object_index is out of range
        ValueError
            If both primary_object_index or [primary_object_x,
            primary_object_v, primary_object_m] is not provided
        """

        if primary_object_index is None:
            if (
                primary_object_x is None
                or primary_object_v is None
                or primary_object_m is None
            ):
                raise ValueError(
                    "primary_object_index or [primary_object_x, \
                    primary_object_v, primary_object_m] must be provided"
                )
        else:
            if primary_object_x is None:
                if self.x.shape[0] <= primary_object_index:
                    raise ValueError(
                        "primary_object_index is out of range for the current system"
                    )
                primary_object_x = self.x[primary_object_index]

            if primary_object_v is None:
                if self.x.shape[0] <= primary_object_index:
                    raise ValueError(
                        "primary_object_index is out of range for the current system"
                    )
                primary_object_v = self.v[primary_object_index]

            if primary_object_m is None:
                if self.x.shape[0] <= primary_object_index:
                    raise ValueError(
                        "primary_object_index is out of range for the current system"
                    )
                primary_object_m = self.m[primary_object_index]

        x, v = utils.keplerian_to_cartesian(
            semi_major_axis=semi_major_axis,
            eccentricity=eccentricity,
            inclination=inclination,
            argument_of_periapsis=argument_of_periapsis,
            longitude_of_ascending_node=longitude_of_ascending_node,
            true_anomaly=true_anomaly,
            total_mass=(primary_object_m + m),
            G=self.G,
        )
        self.add(x + primary_object_x, v + primary_object_v, m)

    def remove(
        self,
        indices: int | list | np.ndarray,
    ) -> None:
        """Remove object(s) from the system

        Parameters
        ----------
        indices : int, list or np.ndarray
            Index or indices of the object(s) to remove

        Raises
        ------
        TypeError
            If indices is not an int, list or np.ndarray
        """
        if isinstance(indices, int):
            indices = np.array([indices])
        elif isinstance(indices, list):
            indices = np.array(indices)
        elif not isinstance(indices, np.ndarray):
            raise TypeError("indices must be an int, list or np.ndarray")

        mask = np.ones(self.objects_count, dtype=bool)
        mask[indices] = False
        self.x = self.x[mask]
        self.v = self.v[mask]
        self.m = self.m[mask]
        self.objects_count -= len(indices)

    def center_of_mass_correction(self) -> None:
        """Set center of mass of position and V_CM to zero"""
        r_cm = np.sum(self.m[:, np.newaxis] * self.x, axis=0) / np.sum(self.m)
        v_cm = np.sum(self.m[:, np.newaxis] * self.v, axis=0) / np.sum(self.m)

        self.x -= r_cm
        self.v -= v_cm

    def sort_by_distance(self, primary_object_index: int) -> None:
        """Sort objects by distance from the origin

        Parameters
        ----------
        primary_object_index : int
            Index of the primary object
        """
        x_diff = self.x - self.x[primary_object_index]
        distances = np.linalg.norm(x_diff, axis=1)
        sorted_indices = np.argsort(distances)
        self.x = self.x[sorted_indices]
        self.v = self.v[sorted_indices]
        self.m = self.m[sorted_indices]

    def save(
        self,
        file_path: Optional[str | Path] = None,
    ) -> None:
        """Save system to a CSV file

        Parameters
        ----------
        file_path : str, optional
            File path to save the system, by default None

        Note
        ----
        This function has the following side effects:
        - Prints a message f"System \"{self.name}\" successfully saved to \"{file_path}\""
        """
        if file_path is None:
            file_path = Path(__file__).parent / "customized_systems.csv"

        with open(file_path, "a", newline="") as file:
            writer = csv.writer(file)
            writer.writerow(
                [self.name, self.G, self.objects_count]
                + self.m.tolist()
                + self.x.flatten().tolist()
                + self.v.flatten().tolist()
            )

        print(f'System "{self.name}" successfully saved to "{file_path}"')

    def load(
        self,
        system_name: str,
        file_path: Optional[str | Path] = None,
    ) -> None:
        """Load system from a CSV file / built-in system

        Parameters
        ----------
        system_name : str
            Name of the system to load
        file_path : str, optional
            File path to load the system from, by default None

        Raises
        ------
        FileNotFoundError
            If a file path is provided but the file is not found
        """
        if file_path is not None:
            if isinstance(file_path, str):
                file_path = Path(file_path)

            if not file_path.is_file():
                raise FileNotFoundError(f"File not found: {file_path}")

        # Remove existing objects
        if self.objects_count > 0:
            self.remove(np.arange(self.objects_count))

        # Load built-in systems
        if file_path is None:
            if system_name in self.BUILT_IN_SYSTEMS:
                if system_name == "circular_binary_orbit":
                    self.G = self.CONSTANT_G
                    R1 = np.array([1.0, 0.0, 0.0])
                    R2 = np.array([-1.0, 0.0, 0.0])
                    V1 = np.array([0.0, 0.5, 0.0])
                    V2 = np.array([0.0, -0.5, 0.0])
                    self.add(R1, V1, 1.0 / self.G)
                    self.add(R2, V2, 1.0 / self.G)

                elif system_name == "eccentric_binary_orbit":
                    self.G = self.CONSTANT_G
                    R1 = np.array([1.0, 0.0, 0.0])
                    R2 = np.array([-1.25, 0.0, 0.0])
                    V1 = np.array([0.0, 0.5, 0.0])
                    V2 = np.array([0.0, -0.625, 0.0])
                    self.add(R1, V1, 1.0 / self.G)
                    self.add(R2, V2, 0.8 / self.G)

                elif system_name == "3d_helix":
                    self.G = self.CONSTANT_G
                    R1 = np.array([0.0, 0.0, -1.0])
                    R2 = np.array([-np.sqrt(3.0) / 2.0, 0.0, 0.5])
                    R3 = np.array([np.sqrt(3.0) / 2.0, 0.0, 0.5])
                    v0 = np.sqrt(1.0 / np.sqrt(3))
                    V1 = np.array([-v0, 0.5, 0.0])
                    V2 = np.array([0.5 * v0, 0.5, (np.sqrt(3.0) / 2.0) * v0])
                    V3 = np.array([0.5 * v0, 0.5, -(np.sqrt(3.0) / 2.0) * v0])
                    self.add(R1, V1, 1.0 / self.G)
                    self.add(R2, V2, 1.0 / self.G)
                    self.add(R3, V3, 1.0 / self.G)

                elif system_name == "sun_earth_moon":
                    self.G = self.CONSTANT_G
                    m = np.array(
                        [
                            GravitationalSystem.SOLAR_SYSTEM_MASSES["Sun"],
                            GravitationalSystem.SOLAR_SYSTEM_MASSES["Earth"],
                            GravitationalSystem.SOLAR_SYSTEM_MASSES["Moon"],
                        ]
                    )

                    R1 = np.array(GravitationalSystem.SOLAR_SYSTEM_POS["Sun"])
                    R2 = np.array(GravitationalSystem.SOLAR_SYSTEM_POS["Earth"])
                    R3 = np.array(GravitationalSystem.SOLAR_SYSTEM_POS["Moon"])
                    V1 = np.array(GravitationalSystem.SOLAR_SYSTEM_VEL["Sun"])
                    V2 = np.array(GravitationalSystem.SOLAR_SYSTEM_VEL["Earth"])
                    V3 = np.array(GravitationalSystem.SOLAR_SYSTEM_VEL["Moon"])
                    self.add(R1, V1, m[0])
                    self.add(R2, V2, m[1])
                    self.add(R3, V3, m[2])

                    self.center_of_mass_correction()

                elif system_name == "figure-8":
                    self.G = self.CONSTANT_G
                    R1 = np.array([0.970043, -0.24308753, 0.0])
                    R2 = np.array([-0.970043, 0.24308753, 0.0])
                    R3 = np.array([0.0, 0.0, 0.0])
                    V1 = np.array([0.466203685, 0.43236573, 0.0])
                    V2 = np.array([0.466203685, 0.43236573, 0.0])
                    V3 = np.array([-0.93240737, -0.86473146, 0.0])
                    # x = np.array([R1, R2, R3])
                    # v = np.array([V1, V2, V3])
                    m = np.array([1.0 / self.G, 1.0 / self.G, 1.0 / self.G])
                    self.add(R1, V1, 1.0 / self.G)
                    self.add(R2, V2, 1.0 / self.G)
                    self.add(R3, V3, 1.0 / self.G)

                elif system_name == "pyth-3-body":
                    self.G = self.CONSTANT_G
                    R1 = np.array([1.0, 3.0, 0.0])
                    R2 = np.array([-2.0, -1.0, 0.0])
                    R3 = np.array([1.0, -1.0, 0.0])
                    V1 = np.array([0.0, 0.0, 0.0])
                    V2 = np.array([0.0, 0.0, 0.0])
                    V3 = np.array([0.0, 0.0, 0.0])
                    self.add(R1, V1, 3.0 / self.G)
                    self.add(R2, V2, 4.0 / self.G)
                    self.add(R3, V3, 5.0 / self.G)

                elif system_name == "solar_system":
                    self.G = self.CONSTANT_G
                    m = np.array(
                        [
                            GravitationalSystem.SOLAR_SYSTEM_MASSES["Sun"],
                            GravitationalSystem.SOLAR_SYSTEM_MASSES["Mercury"],
                            GravitationalSystem.SOLAR_SYSTEM_MASSES["Venus"],
                            GravitationalSystem.SOLAR_SYSTEM_MASSES["Earth"],
                            GravitationalSystem.SOLAR_SYSTEM_MASSES["Mars"],
                            GravitationalSystem.SOLAR_SYSTEM_MASSES["Jupiter"],
                            GravitationalSystem.SOLAR_SYSTEM_MASSES["Saturn"],
                            GravitationalSystem.SOLAR_SYSTEM_MASSES["Uranus"],
                            GravitationalSystem.SOLAR_SYSTEM_MASSES["Neptune"],
                        ]
                    )

                    R1 = np.array(GravitationalSystem.SOLAR_SYSTEM_POS["Sun"])
                    R2 = np.array(GravitationalSystem.SOLAR_SYSTEM_POS["Mercury"])
                    R3 = np.array(GravitationalSystem.SOLAR_SYSTEM_POS["Venus"])
                    R4 = np.array(GravitationalSystem.SOLAR_SYSTEM_POS["Earth"])
                    R5 = np.array(GravitationalSystem.SOLAR_SYSTEM_POS["Mars"])
                    R6 = np.array(GravitationalSystem.SOLAR_SYSTEM_POS["Jupiter"])
                    R7 = np.array(GravitationalSystem.SOLAR_SYSTEM_POS["Saturn"])
                    R8 = np.array(GravitationalSystem.SOLAR_SYSTEM_POS["Uranus"])
                    R9 = np.array(GravitationalSystem.SOLAR_SYSTEM_POS["Neptune"])

                    V1 = np.array(GravitationalSystem.SOLAR_SYSTEM_VEL["Sun"])
                    V2 = np.array(GravitationalSystem.SOLAR_SYSTEM_VEL["Mercury"])
                    V3 = np.array(GravitationalSystem.SOLAR_SYSTEM_VEL["Venus"])
                    V4 = np.array(GravitationalSystem.SOLAR_SYSTEM_VEL["Earth"])
                    V5 = np.array(GravitationalSystem.SOLAR_SYSTEM_VEL["Mars"])
                    V6 = np.array(GravitationalSystem.SOLAR_SYSTEM_VEL["Jupiter"])
                    V7 = np.array(GravitationalSystem.SOLAR_SYSTEM_VEL["Saturn"])
                    V8 = np.array(GravitationalSystem.SOLAR_SYSTEM_VEL["Uranus"])
                    V9 = np.array(GravitationalSystem.SOLAR_SYSTEM_VEL["Neptune"])

                    self.add(R1, V1, m[0])
                    self.add(R2, V2, m[1])
                    self.add(R3, V3, m[2])
                    self.add(R4, V4, m[3])
                    self.add(R5, V5, m[4])
                    self.add(R6, V6, m[5])
                    self.add(R7, V7, m[6])
                    self.add(R8, V8, m[7])
                    self.add(R9, V9, m[8])

                    self.center_of_mass_correction()

                elif system_name == "solar_system_plus":
                    self.G = self.CONSTANT_G
                    m = np.array(
                        [
                            GravitationalSystem.SOLAR_SYSTEM_MASSES["Sun"],
                            GravitationalSystem.SOLAR_SYSTEM_MASSES["Mercury"],
                            GravitationalSystem.SOLAR_SYSTEM_MASSES["Venus"],
                            GravitationalSystem.SOLAR_SYSTEM_MASSES["Earth"],
                            GravitationalSystem.SOLAR_SYSTEM_MASSES["Mars"],
                            GravitationalSystem.SOLAR_SYSTEM_MASSES["Jupiter"],
                            GravitationalSystem.SOLAR_SYSTEM_MASSES["Saturn"],
                            GravitationalSystem.SOLAR_SYSTEM_MASSES["Uranus"],
                            GravitationalSystem.SOLAR_SYSTEM_MASSES["Neptune"],
                            GravitationalSystem.SOLAR_SYSTEM_MASSES["Pluto"],
                            GravitationalSystem.SOLAR_SYSTEM_MASSES["Ceres"],
                            GravitationalSystem.SOLAR_SYSTEM_MASSES["Vesta"],
                        ]
                    )

                    R1 = np.array(GravitationalSystem.SOLAR_SYSTEM_POS["Sun"])
                    R2 = np.array(GravitationalSystem.SOLAR_SYSTEM_POS["Mercury"])
                    R3 = np.array(GravitationalSystem.SOLAR_SYSTEM_POS["Venus"])
                    R4 = np.array(GravitationalSystem.SOLAR_SYSTEM_POS["Earth"])
                    R5 = np.array(GravitationalSystem.SOLAR_SYSTEM_POS["Mars"])
                    R6 = np.array(GravitationalSystem.SOLAR_SYSTEM_POS["Jupiter"])
                    R7 = np.array(GravitationalSystem.SOLAR_SYSTEM_POS["Saturn"])
                    R8 = np.array(GravitationalSystem.SOLAR_SYSTEM_POS["Uranus"])
                    R9 = np.array(GravitationalSystem.SOLAR_SYSTEM_POS["Neptune"])
                    R10 = np.array(GravitationalSystem.SOLAR_SYSTEM_POS["Pluto"])
                    R11 = np.array(GravitationalSystem.SOLAR_SYSTEM_POS["Ceres"])
                    R12 = np.array(GravitationalSystem.SOLAR_SYSTEM_POS["Vesta"])

                    V1 = np.array(GravitationalSystem.SOLAR_SYSTEM_VEL["Sun"])
                    V2 = np.array(GravitationalSystem.SOLAR_SYSTEM_VEL["Mercury"])
                    V3 = np.array(GravitationalSystem.SOLAR_SYSTEM_VEL["Venus"])
                    V4 = np.array(GravitationalSystem.SOLAR_SYSTEM_VEL["Earth"])
                    V5 = np.array(GravitationalSystem.SOLAR_SYSTEM_VEL["Mars"])
                    V6 = np.array(GravitationalSystem.SOLAR_SYSTEM_VEL["Jupiter"])
                    V7 = np.array(GravitationalSystem.SOLAR_SYSTEM_VEL["Saturn"])
                    V8 = np.array(GravitationalSystem.SOLAR_SYSTEM_VEL["Uranus"])
                    V9 = np.array(GravitationalSystem.SOLAR_SYSTEM_VEL["Neptune"])
                    V10 = np.array(GravitationalSystem.SOLAR_SYSTEM_VEL["Pluto"])
                    V11 = np.array(GravitationalSystem.SOLAR_SYSTEM_VEL["Ceres"])
                    V12 = np.array(GravitationalSystem.SOLAR_SYSTEM_VEL["Vesta"])

                    self.add(R1, V1, m[0])
                    self.add(R2, V2, m[1])
                    self.add(R3, V3, m[2])
                    self.add(R4, V4, m[3])
                    self.add(R5, V5, m[4])
                    self.add(R6, V6, m[5])
                    self.add(R7, V7, m[6])
                    self.add(R8, V8, m[7])
                    self.add(R9, V9, m[8])
                    self.add(R10, V10, m[9])
                    self.add(R11, V11, m[10])
                    self.add(R12, V12, m[11])

                    self.center_of_mass_correction()

            else:
                file_path = Path(__file__).parent / "customized_systems.csv"
                if not file_path.is_file():
                    err_msg = (
                        f'load: system name "{system_name}" not found in built-in systems, and'
                        f' default customized systems file not found: "{file_path}"'
                    )
                    raise ValueError(err_msg)

                # Load system from default customized systems file
                else:
                    loaded_system_flag = False
                    with open(file_path, "r") as file:
                        reader = csv.reader(file)
                        for row in reader:
                            if row[0] == system_name:
                                self.name = system_name
                                self.G = float(row[1])
                                objects_count = int(row[2])
                                m = np.zeros(objects_count)
                                for i in range(objects_count):
                                    m[i] = float(row[3 + i])

                                x = np.zeros((objects_count, 3))
                                v = np.zeros((objects_count, 3))
                                for i in range(objects_count):
                                    x[i] = np.array(
                                        row[
                                            (3 + objects_count + i * 3) : (
                                                3 + objects_count + i * 3 + 3
                                            )
                                        ]
                                    )
                                    v[i] = np.array(
                                        row[
                                            (
                                                3
                                                + objects_count
                                                + objects_count * 3
                                                + i * 3
                                            ) : (
                                                3
                                                + objects_count
                                                + objects_count * 3
                                                + i * 3
                                                + 3
                                            )
                                        ]
                                    )

                                self.add(x, v, m)
                                loaded_system_flag = True

                    if not loaded_system_flag:
                        err_msg = (
                            f'load: system name "{system_name}" not recognized in '
                            f'built-in systems and customized systems file: "{file_path}"'
                        )
                        raise ValueError(err_msg)

        # Load system from given file path
        else:
            loaded_system_flag = False
            with open(file_path, "r") as file:
                reader = csv.reader(file)
                for row in reader:
                    if row[0] == system_name:
                        self.name = system_name
                        self.G = float(row[1])
                        objects_count = int(row[2])
                        m = np.zeros(objects_count)
                        for i in range(objects_count):
                            m[i] = float(row[3 + i])

                        x = np.zeros((objects_count, 3))
                        v = np.zeros((objects_count, 3))
                        for i in range(objects_count):
                            x[i] = np.array(
                                row[
                                    (3 + objects_count + i * 3) : (
                                        3 + objects_count + i * 3 + 3
                                    )
                                ]
                            )
                            v[i] = np.array(
                                row[
                                    (3 + objects_count + objects_count * 3 + i * 3) : (
                                        3
                                        + objects_count
                                        + objects_count * 3
                                        + i * 3
                                        + 3
                                    )
                                ]
                            )

                        self.add(x, v, m)
                        loaded_system_flag = True
            if not loaded_system_flag:
                err_msg = (
                    f'load: system name "{system_name}" not recognized in '
                    f'given file: "{file_path}"'
                )
                raise ValueError(err_msg)

        self.name = system_name

    def plot_2d_system(
        self,
        colors: Optional[list[str]] = None,
        labels: Optional[list[str]] = None,
        legend: bool = False,
        xlabel: str = "$x$ (AU)",
        ylabel: str = "$y$ (AU)",
        title: Optional[str] = None,
        marker: str = "o",
        markersize: int = 6,
        save_fig: bool = False,
        save_fig_path: Optional[str | Path] = None,
    ) -> None:
        initial_state = np.concatenate(
            [
                self.x.flatten(),
                self.v.flatten(),
            ]
        )[np.newaxis, :]

        plotting.plot_2d_trajectory(
            initial_state,
            colors,
            labels,
            legend,
            xlabel,
            ylabel,
            title,
            marker,
            markersize,
            save_fig,
            save_fig_path,
        )

    def plot_3d_system(
        self,
        colors: Optional[list[str]] = None,
        labels: Optional[list[str]] = None,
        legend: bool = False,
        xlabel: str = "$x$ (AU)",
        ylabel: str = "$y$ (AU)",
        zlabel: str = "$z$ (AU)",
        title: Optional[str] = None,
        marker: str = "o",
        markersize: int = 6,
        save_fig: bool = False,
        save_fig_path: Optional[str | Path] = None,
    ) -> None:
        initial_state = np.concatenate(
            [
                self.x.flatten(),
                self.v.flatten(),
            ]
        )[np.newaxis, :]

        plotting.plot_3d_trajectory(
            initial_state,
            colors,
            labels,
            legend,
            xlabel,
            ylabel,
            zlabel,
            title,
            marker,
            markersize,
            save_fig,
            save_fig_path,
        )
